//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MobileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MobileResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso.
        /// </summary>
        internal static string srv_access_type_access {
            get {
                return ResourceManager.GetString("srv_access_type_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de autenticación.
        /// </summary>
        internal static string srv_auth_error {
            get {
                return ResourceManager.GetString("srv_auth_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de autenticación, el dispositovo no es valido.
        /// </summary>
        internal static string srv_auth_error_mac {
            get {
                return ResourceManager.GetString("srv_auth_error_mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClienteID no válido.
        /// </summary>
        internal static string srv_cliente_id_invalid {
            get {
                return ResourceManager.GetString("srv_cliente_id_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este código no es valido.
        /// </summary>
        internal static string srv_codigo_no_valido {
            get {
                return ResourceManager.GetString("srv_codigo_no_valido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validación código cliente.
        /// </summary>
        internal static string srv_cod_error {
            get {
                return ResourceManager.GetString("srv_cod_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string srv_default_error {
            get {
                return ResourceManager.GetString("srv_default_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento no válido o inactivo.
        /// </summary>
        internal static string srv_element_invalid_inactive {
            get {
                return ResourceManager.GetString("srv_element_invalid_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string srv_error {
            get {
                return ResourceManager.GetString("srv_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Update.
        /// </summary>
        internal static string srv_error_update {
            get {
                return ResourceManager.GetString("srv_error_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción de servidor.
        /// </summary>
        internal static string srv_exception {
            get {
                return ResourceManager.GetString("srv_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        internal static string srv_form_comment {
            get {
                return ResourceManager.GetString("srv_form_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotos Min: .
        /// </summary>
        internal static string srv_form_photos {
            get {
                return ResourceManager.GetString("srv_form_photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotos (opcional).
        /// </summary>
        internal static string srv_form_photos_optional {
            get {
                return ResourceManager.GetString("srv_form_photos_optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento obligatorio incompleto.
        /// </summary>
        internal static string srv_form_required_element {
            get {
                return ResourceManager.GetString("srv_form_required_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string srv_form_send {
            get {
                return ResourceManager.GetString("srv_form_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obra Civil.
        /// </summary>
        internal static string srv_install_type_civil_work {
            get {
                return ResourceManager.GetString("srv_install_type_civil_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Técnica.
        /// </summary>
        internal static string srv_install_type_technical {
            get {
                return ResourceManager.GetString("srv_install_type_technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoríaID inválido.
        /// </summary>
        internal static string srv_invalid_category_id {
            get {
                return ResourceManager.GetString("srv_invalid_category_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de formulario no válidos.
        /// </summary>
        internal static string srv_invalid_form_data {
            get {
                return ResourceManager.GetString("srv_invalid_form_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de elemento no válido.
        /// </summary>
        internal static string srv_invalid_inventory_element_id {
            get {
                return ResourceManager.GetString("srv_invalid_inventory_element_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaisID no válido.
        /// </summary>
        internal static string srv_invalid_pais_id {
            get {
                return ResourceManager.GetString("srv_invalid_pais_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProvinciaID no válido.
        /// </summary>
        internal static string srv_invalid_provincia_id {
            get {
                return ResourceManager.GetString("srv_invalid_provincia_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto Tipo inválido.
        /// </summary>
        internal static string srv_invalid_proyecto_tipo {
            get {
                return ResourceManager.GetString("srv_invalid_proyecto_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionPaisID no válido.
        /// </summary>
        internal static string srv_invalid_region_pais_id {
            get {
                return ResourceManager.GetString("srv_invalid_region_pais_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmplazamientoID inválido.
        /// </summary>
        internal static string srv_invalid_site_id {
            get {
                return ResourceManager.GetString("srv_invalid_site_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario invalido.
        /// </summary>
        internal static string srv_invalid_user {
            get {
                return ResourceManager.GetString("srv_invalid_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de usuario o proyecto no válido.
        /// </summary>
        internal static string srv_invalid_user_or_project_id {
            get {
                return ResourceManager.GetString("srv_invalid_user_or_project_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correctivo.
        /// </summary>
        internal static string srv_maintenance_type_corrective {
            get {
                return ResourceManager.GetString("srv_maintenance_type_corrective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio bajo demanda.
        /// </summary>
        internal static string srv_maintenance_type_low_demand_service {
            get {
                return ResourceManager.GetString("srv_maintenance_type_low_demand_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preventivo.
        /// </summary>
        internal static string srv_maintenance_type_preventive {
            get {
                return ResourceManager.GetString("srv_maintenance_type_preventive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tareas programadas.
        /// </summary>
        internal static string srv_maintenance_type_programmed_tasks {
            get {
                return ResourceManager.GetString("srv_maintenance_type_programmed_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron categorías.
        /// </summary>
        internal static string srv_no_categorias_sitios {
            get {
                return ResourceManager.GetString("srv_no_categorias_sitios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Empresas Proveedoras.
        /// </summary>
        internal static string srv_no_empresas_proveedoras {
            get {
                return ResourceManager.GetString("srv_no_empresas_proveedoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Inventario Categorías.
        /// </summary>
        internal static string srv_no_inventario_categorias {
            get {
                return ResourceManager.GetString("srv_no_inventario_categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron InventarioElementos.
        /// </summary>
        internal static string srv_no_inventory_elements {
            get {
                return ResourceManager.GetString("srv_no_inventory_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Municipios.
        /// </summary>
        internal static string srv_no_municipios {
            get {
                return ResourceManager.GetString("srv_no_municipios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Provincias.
        /// </summary>
        internal static string srv_no_provincias {
            get {
                return ResourceManager.GetString("srv_no_provincias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Regiones.
        /// </summary>
        internal static string srv_no_regiones_paises {
            get {
                return ResourceManager.GetString("srv_no_regiones_paises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron tamaños de emplazamientos.
        /// </summary>
        internal static string srv_no_tamanos_emplazamientos {
            get {
                return ResourceManager.GetString("srv_no_tamanos_emplazamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron tipos de edificios.
        /// </summary>
        internal static string srv_no_tipos_edificios {
            get {
                return ResourceManager.GetString("srv_no_tipos_edificios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron tipos de emplazamientos.
        /// </summary>
        internal static string srv_no_tipos_emplazamientos {
            get {
                return ResourceManager.GetString("srv_no_tipos_emplazamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string srv_ok {
            get {
                return ResourceManager.GetString("srv_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto no encontrado.
        /// </summary>
        internal static string srv_project_not_found {
            get {
                return ResourceManager.GetString("srv_project_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmplazamientoID no váido.
        /// </summary>
        internal static string srv_site_invalid_id {
            get {
                return ResourceManager.GetString("srv_site_invalid_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tareas completadas.
        /// </summary>
        internal static string srv_state_msg_tasks_complete {
            get {
                return ResourceManager.GetString("srv_state_msg_tasks_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eléctrica.
        /// </summary>
        internal static string srv_uninstall_type_electrical {
            get {
                return ResourceManager.GetString("srv_uninstall_type_electrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Técnica.
        /// </summary>
        internal static string srv_uninstall_type_technical {
            get {
                return ResourceManager.GetString("srv_uninstall_type_technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no válido o inactivo.
        /// </summary>
        internal static string srv_user_invalid_inactive {
            get {
                return ResourceManager.GetString("srv_user_invalid_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Denegacion Acceso.
        /// </summary>
        internal static string state_ACCESO_DENEGADO_date {
            get {
                return ResourceManager.GetString("state_ACCESO_DENEGADO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denegar Acceso.
        /// </summary>
        internal static string state_ACCESO_DENEGADO_next {
            get {
                return ResourceManager.GetString("state_ACCESO_DENEGADO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Acceso Finalizado.
        /// </summary>
        internal static string state_ACCESO_FINALIZADO_date {
            get {
                return ResourceManager.GetString("state_ACCESO_FINALIZADO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso Finalizado.
        /// </summary>
        internal static string state_ACCESO_FINALIZADO_next {
            get {
                return ResourceManager.GetString("state_ACCESO_FINALIZADO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha en Revisión.
        /// </summary>
        internal static string state_BLOQUEADO_date {
            get {
                return ResourceManager.GetString("state_BLOQUEADO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        internal static string state_BLOQUEADO_next {
            get {
                return ResourceManager.GetString("state_BLOQUEADO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Cancelación por Cliente.
        /// </summary>
        internal static string state_CANCELADO_CLIENTE_date {
            get {
                return ResourceManager.GetString("state_CANCELADO_CLIENTE_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelación por Cliente.
        /// </summary>
        internal static string state_CANCELADO_CLIENTE_next {
            get {
                return ResourceManager.GetString("state_CANCELADO_CLIENTE_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Rechazado.
        /// </summary>
        internal static string state_CANCELADO_date {
            get {
                return ResourceManager.GetString("state_CANCELADO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string state_CANCELADO_next {
            get {
                return ResourceManager.GetString("state_CANCELADO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Carga Inicial.
        /// </summary>
        internal static string state_CARGA_INICIAL_date {
            get {
                return ResourceManager.GetString("state_CARGA_INICIAL_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga inicial.
        /// </summary>
        internal static string state_CARGA_INICIAL_next {
            get {
                return ResourceManager.GetString("state_CARGA_INICIAL_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desestimado.
        /// </summary>
        internal static string state_CERRADO_ABORT_date {
            get {
                return ResourceManager.GetString("state_CERRADO_ABORT_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desistir.
        /// </summary>
        internal static string state_CERRADO_ABORT_next {
            get {
                return ResourceManager.GetString("state_CERRADO_ABORT_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Comunicación Previa.
        /// </summary>
        internal static string state_COMUNICACION_PREVIA_date {
            get {
                return ResourceManager.GetString("state_COMUNICACION_PREVIA_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunicación Previa.
        /// </summary>
        internal static string state_COMUNICACION_PREVIA_next {
            get {
                return ResourceManager.GetString("state_COMUNICACION_PREVIA_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Cancelar Contrato.
        /// </summary>
        internal static string state_CONTRATO_CANCELADO_date {
            get {
                return ResourceManager.GetString("state_CONTRATO_CANCELADO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar Contrato.
        /// </summary>
        internal static string state_CONTRATO_CANCELADO_next {
            get {
                return ResourceManager.GetString("state_CONTRATO_CANCELADO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desbloqueado.
        /// </summary>
        internal static string state_DESBLOQUEADO_date {
            get {
                return ResourceManager.GetString("state_DESBLOQUEADO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloqueado.
        /// </summary>
        internal static string state_DESBLOQUEADO_next {
            get {
                return ResourceManager.GetString("state_DESBLOQUEADO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desestimado.
        /// </summary>
        internal static string state_DESISTIDO_date {
            get {
                return ResourceManager.GetString("state_DESISTIDO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desistir.
        /// </summary>
        internal static string state_DESISTIDO_next {
            get {
                return ResourceManager.GetString("state_DESISTIDO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Revisión.
        /// </summary>
        internal static string state_EN_REVISION_date {
            get {
                return ResourceManager.GetString("state_EN_REVISION_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisar.
        /// </summary>
        internal static string state_EN_REVISION_next {
            get {
                return ResourceManager.GetString("state_EN_REVISION_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Integración.
        /// </summary>
        internal static string state_INTEGRACION_COMPLETADA_date {
            get {
                return ResourceManager.GetString("state_INTEGRACION_COMPLETADA_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Instalación.
        /// </summary>
        internal static string state_INTEGRACION_COMPLETADA_next {
            get {
                return ResourceManager.GetString("state_INTEGRACION_COMPLETADA_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Lanzamiento.
        /// </summary>
        internal static string state_LANZADO_date {
            get {
                return ResourceManager.GetString("state_LANZADO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanzar.
        /// </summary>
        internal static string state_LANZADO_next {
            get {
                return ResourceManager.GetString("state_LANZADO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Cesíon Medidor.
        /// </summary>
        internal static string state_MEDIDOR_CEDIDO_date {
            get {
                return ResourceManager.GetString("state_MEDIDOR_CEDIDO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceder Medidor.
        /// </summary>
        internal static string state_MEDIDOR_CEDIDO_next {
            get {
                return ResourceManager.GetString("state_MEDIDOR_CEDIDO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Certificación obra.
        /// </summary>
        internal static string state_OBRA_CERTIFICADA_date {
            get {
                return ResourceManager.GetString("state_OBRA_CERTIFICADA_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificar Obra.
        /// </summary>
        internal static string state_OBRA_CERTIFICADA_next {
            get {
                return ResourceManager.GetString("state_OBRA_CERTIFICADA_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Obra.
        /// </summary>
        internal static string state_OBRA_EN_CURSO_date {
            get {
                return ResourceManager.GetString("state_OBRA_EN_CURSO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Obra.
        /// </summary>
        internal static string state_OBRA_EN_CURSO_next {
            get {
                return ResourceManager.GetString("state_OBRA_EN_CURSO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Finalización obra.
        /// </summary>
        internal static string state_OBRA_FINALIZADA_date {
            get {
                return ResourceManager.GetString("state_OBRA_FINALIZADA_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar Obra.
        /// </summary>
        internal static string state_OBRA_FINALIZADA_next {
            get {
                return ResourceManager.GetString("state_OBRA_FINALIZADA_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Acceso.
        /// </summary>
        internal static string state_PENDIENTE_ACCESO_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_ACCESO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente Acceso.
        /// </summary>
        internal static string state_PENDIENTE_ACCESO_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_ACCESO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Ampliación Eléctrica.
        /// </summary>
        internal static string state_PENDIENTE_AMPLIACION_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_AMPLIACION_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalar Transmisión.
        /// </summary>
        internal static string state_PENDIENTE_AMPLIACION_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_AMPLIACION_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Aprobación Acceso.
        /// </summary>
        internal static string state_PENDIENTE_APROBACION_ACCESO_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_APROBACION_ACCESO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Acceso.
        /// </summary>
        internal static string state_PENDIENTE_APROBACION_ACCESO_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_APROBACION_ACCESO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Autorización.
        /// </summary>
        internal static string state_PENDIENTE_AUTORIZACION_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_AUTORIZACION_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente Autorización.
        /// </summary>
        internal static string state_PENDIENTE_AUTORIZACION_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_AUTORIZACION_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Baja.
        /// </summary>
        internal static string state_PENDIENTE_BAJA_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_BAJA_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envío Solicitud Baja.
        /// </summary>
        internal static string state_PENDIENTE_BAJA_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_BAJA_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Desinstalación.
        /// </summary>
        internal static string state_PENDIENTE_DESINSTALACION_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_DESINSTALACION_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar Desinstalación.
        /// </summary>
        internal static string state_PENDIENTE_DESINSTALACION_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_DESINSTALACION_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Devolución Llave.
        /// </summary>
        internal static string state_PENDIENTE_DEVOLUCION_LLAVE_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_DEVOLUCION_LLAVE_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente Devolución Llave.
        /// </summary>
        internal static string state_PENDIENTE_DEVOLUCION_LLAVE_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_DEVOLUCION_LLAVE_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Instalación Equipos.
        /// </summary>
        internal static string state_PENDIENTE_EQUIPOS_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_EQUIPOS_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar Equipos.
        /// </summary>
        internal static string state_PENDIENTE_EQUIPOS_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_EQUIPOS_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Inicio Obra.
        /// </summary>
        internal static string state_PENDIENTE_INICIO_OBRA_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_INICIO_OBRA_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificar Inicio de Obra.
        /// </summary>
        internal static string state_PENDIENTE_INICIO_OBRA_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_INICIO_OBRA_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Llave.
        /// </summary>
        internal static string state_PENDIENTE_LLAVE_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_LLAVE_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente Llave.
        /// </summary>
        internal static string state_PENDIENTE_LLAVE_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_LLAVE_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Obra.
        /// </summary>
        internal static string state_PENDIENTE_OBRA_CIVIL_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_OBRA_CIVIL_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Retirada Obra Civil.
        /// </summary>
        internal static string state_PENDIENTE_OBRA_CIVIL_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_OBRA_CIVIL_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha On Air.
        /// </summary>
        internal static string state_PENDIENTE_ON_AIR_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_ON_AIR_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Air.
        /// </summary>
        internal static string state_PENDIENTE_ON_AIR_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_ON_AIR_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Operador.
        /// </summary>
        internal static string state_PENDIENTE_OPERADOR_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_OPERADOR_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente Operador.
        /// </summary>
        internal static string state_PENDIENTE_OPERADOR_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_OPERADOR_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Permisos.
        /// </summary>
        internal static string state_PENDIENTE_PERMISOS_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_PERMISOS_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar Presupuesto.
        /// </summary>
        internal static string state_PENDIENTE_PERMISOS_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_PERMISOS_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Planificar Visita Técnica.
        /// </summary>
        internal static string state_PENDIENTE_PLANIFICAR_VISITA_TECNICA_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_PLANIFICAR_VISITA_TECNICA_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Visita Técnica.
        /// </summary>
        internal static string state_PENDIENTE_PLANIFICAR_VISITA_TECNICA_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_PLANIFICAR_VISITA_TECNICA_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Presupuesto.
        /// </summary>
        internal static string state_PENDIENTE_PRESUPUESTO_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_PRESUPUESTO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Presupuesto.
        /// </summary>
        internal static string state_PENDIENTE_PRESUPUESTO_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_PRESUPUESTO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Replanteo.
        /// </summary>
        internal static string state_PENDIENTE_REPLANTEO_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_REPLANTEO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificar Replanteo.
        /// </summary>
        internal static string state_PENDIENTE_REPLANTEO_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_REPLANTEO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Revisión Presupuesto.
        /// </summary>
        internal static string state_PENDIENTE_REVISION_PRESUPUESTO_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_REVISION_PRESUPUESTO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Presupuesto.
        /// </summary>
        internal static string state_PENDIENTE_REVISION_PRESUPUESTO_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_REVISION_PRESUPUESTO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Envío Baja.
        /// </summary>
        internal static string state_PENDIENTE_SOLICITUD_BAJA_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_SOLICITUD_BAJA_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Baja.
        /// </summary>
        internal static string state_PENDIENTE_SOLICITUD_BAJA_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_SOLICITUD_BAJA_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pendiente Solicitud Desinstalación.
        /// </summary>
        internal static string state_PENDIENTE_SOLICITUD_DESINSTALACION_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_SOLICITUD_DESINSTALACION_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente solicitud desinstalación.
        /// </summary>
        internal static string state_PENDIENTE_SOLICITUD_DESINSTALACION_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_SOLICITUD_DESINSTALACION_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Subsanación.
        /// </summary>
        internal static string state_PENDIENTE_SUBSANACION_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_SUBSANACION_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente Subsanación Final.
        /// </summary>
        internal static string state_PENDIENTE_SUBSANACION_FINAL_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_SUBSANACION_FINAL_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Subsanación.
        /// </summary>
        internal static string state_PENDIENTE_SUBSANACION_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_SUBSANACION_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Instalación Transmisión.
        /// </summary>
        internal static string state_PENDIENTE_TRANSMISION_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_TRANSMISION_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Instalación Transmisión.
        /// </summary>
        internal static string state_PENDIENTE_TRANSMISION_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_TRANSMISION_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Validación.
        /// </summary>
        internal static string state_PENDIENTE_VALIDACION_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_VALIDACION_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsanar.
        /// </summary>
        internal static string state_PENDIENTE_VALIDACION_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_VALIDACION_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Prevista Visita Técnica.
        /// </summary>
        internal static string state_PENDIENTE_VISITA_TECNICA_date {
            get {
                return ResourceManager.GetString("state_PENDIENTE_VISITA_TECNICA_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proponer Fecha Visita.
        /// </summary>
        internal static string state_PENDIENTE_VISITA_TECNICA_next {
            get {
                return ResourceManager.GetString("state_PENDIENTE_VISITA_TECNICA_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Presentación Presupuesto.
        /// </summary>
        internal static string state_PRESUPUESTO_PRESENTADO_date {
            get {
                return ResourceManager.GetString("state_PRESUPUESTO_PRESENTADO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentar Presupuesto.
        /// </summary>
        internal static string state_PRESUPUESTO_PRESENTADO_next {
            get {
                return ResourceManager.GetString("state_PRESUPUESTO_PRESENTADO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Propuesta propiedad.
        /// </summary>
        internal static string state_PROPUESTA_PROPIEDAD_date {
            get {
                return ResourceManager.GetString("state_PROPUESTA_PROPIEDAD_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propuesta propiedad.
        /// </summary>
        internal static string state_PROPUESTA_PROPIEDAD_next {
            get {
                return ResourceManager.GetString("state_PROPUESTA_PROPIEDAD_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Carga Inicial.
        /// </summary>
        internal static string state_READY_TO_INSTALL_date {
            get {
                return ResourceManager.GetString("state_READY_TO_INSTALL_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo para Instalar.
        /// </summary>
        internal static string state_READY_TO_INSTALL_next {
            get {
                return ResourceManager.GetString("state_READY_TO_INSTALL_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Rechazado.
        /// </summary>
        internal static string state_RECHAZADO_date {
            get {
                return ResourceManager.GetString("state_RECHAZADO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazado.
        /// </summary>
        internal static string state_RECHAZADO_next {
            get {
                return ResourceManager.GetString("state_RECHAZADO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Seguimiento.
        /// </summary>
        internal static string state_SEGUIMIENTO_date {
            get {
                return ResourceManager.GetString("state_SEGUIMIENTO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimiento.
        /// </summary>
        internal static string state_SEGUIMIENTO_next {
            get {
                return ResourceManager.GetString("state_SEGUIMIENTO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desinstalación.
        /// </summary>
        internal static string state_SITIO_DESINSTALADO_date {
            get {
                return ResourceManager.GetString("state_SITIO_DESINSTALADO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Desinstalación.
        /// </summary>
        internal static string state_SITIO_DESINSTALADO_next {
            get {
                return ResourceManager.GetString("state_SITIO_DESINSTALADO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Solicitud Acceso.
        /// </summary>
        internal static string state_SOLICITUD_ACCESO_date {
            get {
                return ResourceManager.GetString("state_SOLICITUD_ACCESO_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Acceso.
        /// </summary>
        internal static string state_SOLICITUD_ACCESO_next {
            get {
                return ResourceManager.GetString("state_SOLICITUD_ACCESO_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Validación Final.
        /// </summary>
        internal static string state_VALIDACION_FINAL_date {
            get {
                return ResourceManager.GetString("state_VALIDACION_FINAL_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificación Instalación.
        /// </summary>
        internal static string state_VALIDACION_FINAL_next {
            get {
                return ResourceManager.GetString("state_VALIDACION_FINAL_next", resourceCulture);
            }
        }
    }
}
