//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MobileResources_GIS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobileResources_GIS() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MobileResources_GIS", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso.
        /// </summary>
        internal static string srv_access_type_access {
            get {
                return ResourceManager.GetString("srv_access_type_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de autenticación.
        /// </summary>
        internal static string srv_auth_error {
            get {
                return ResourceManager.GetString("srv_auth_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de autenticación, el dispositovo no es valido.
        /// </summary>
        internal static string srv_auth_error_mac {
            get {
                return ResourceManager.GetString("srv_auth_error_mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ClienteID no válido.
        /// </summary>
        internal static string srv_cliente_id_invalid {
            get {
                return ResourceManager.GetString("srv_cliente_id_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este código no es valido.
        /// </summary>
        internal static string srv_codigo_no_valido {
            get {
                return ResourceManager.GetString("srv_codigo_no_valido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error validación código cliente.
        /// </summary>
        internal static string srv_cod_error {
            get {
                return ResourceManager.GetString("srv_cod_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string srv_default_error {
            get {
                return ResourceManager.GetString("srv_default_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento no válido o inactivo.
        /// </summary>
        internal static string srv_element_invalid_inactive {
            get {
                return ResourceManager.GetString("srv_element_invalid_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string srv_error {
            get {
                return ResourceManager.GetString("srv_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe el emplazamiento..
        /// </summary>
        internal static string srv_error_informacion_emplazamineto {
            get {
                return ResourceManager.GetString("srv_error_informacion_emplazamineto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe el seguimiento..
        /// </summary>
        internal static string srv_error_informacion_seguimiento {
            get {
                return ResourceManager.GetString("srv_error_informacion_seguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Update.
        /// </summary>
        internal static string srv_error_update {
            get {
                return ResourceManager.GetString("srv_error_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El emplazamiento ya se validó por otro usuario..
        /// </summary>
        internal static string srv_estado_distinto {
            get {
                return ResourceManager.GetString("srv_estado_distinto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excepción de servidor.
        /// </summary>
        internal static string srv_exception {
            get {
                return ResourceManager.GetString("srv_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario.
        /// </summary>
        internal static string srv_form_comment {
            get {
                return ResourceManager.GetString("srv_form_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos (opcional).
        /// </summary>
        internal static string srv_form_photos_optional {
            get {
                return ResourceManager.GetString("srv_form_photos_optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento obligatorio incompleto.
        /// </summary>
        internal static string srv_form_required_element {
            get {
                return ResourceManager.GetString("srv_form_required_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string srv_form_send {
            get {
                return ResourceManager.GetString("srv_form_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CategoríaID inválido.
        /// </summary>
        internal static string srv_invalid_category_id {
            get {
                return ResourceManager.GetString("srv_invalid_category_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de formulario no válidos.
        /// </summary>
        internal static string srv_invalid_form_data {
            get {
                return ResourceManager.GetString("srv_invalid_form_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID de elemento no válido.
        /// </summary>
        internal static string srv_invalid_inventory_element_id {
            get {
                return ResourceManager.GetString("srv_invalid_inventory_element_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PaisID no válido.
        /// </summary>
        internal static string srv_invalid_pais_id {
            get {
                return ResourceManager.GetString("srv_invalid_pais_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ProvinciaID no válido.
        /// </summary>
        internal static string srv_invalid_provincia_id {
            get {
                return ResourceManager.GetString("srv_invalid_provincia_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto Tipo inválido.
        /// </summary>
        internal static string srv_invalid_proyecto_tipo {
            get {
                return ResourceManager.GetString("srv_invalid_proyecto_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RegionPaisID no válido.
        /// </summary>
        internal static string srv_invalid_region_pais_id {
            get {
                return ResourceManager.GetString("srv_invalid_region_pais_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EmplazamientoID inválido.
        /// </summary>
        internal static string srv_invalid_site_id {
            get {
                return ResourceManager.GetString("srv_invalid_site_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario invalido.
        /// </summary>
        internal static string srv_invalid_user {
            get {
                return ResourceManager.GetString("srv_invalid_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID de usuario o proyecto no válido.
        /// </summary>
        internal static string srv_invalid_user_or_project_id {
            get {
                return ResourceManager.GetString("srv_invalid_user_or_project_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correctivo.
        /// </summary>
        internal static string srv_maintenance_type_corrective {
            get {
                return ResourceManager.GetString("srv_maintenance_type_corrective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio bajo demanda.
        /// </summary>
        internal static string srv_maintenance_type_low_demand_service {
            get {
                return ResourceManager.GetString("srv_maintenance_type_low_demand_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preventivo.
        /// </summary>
        internal static string srv_maintenance_type_preventive {
            get {
                return ResourceManager.GetString("srv_maintenance_type_preventive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no válido o inactivo.
        /// </summary>
        internal static string srv_user_invalid_inactive {
            get {
                return ResourceManager.GetString("srv_user_invalid_inactive", resourceCulture);
            }
        }
    }
}
