//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeCore.BackEnd.Translations.ResourcesFiles {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralTranslations() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeCore.BackEnd.Translations.ResourcesFiles.GeneralTranslations", typeof(GeneralTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string CodeContractDate {
            get {
                return ResourceManager.GetString("CodeContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Business Process.
        /// </summary>
        internal static string strBusinessProcess {
            get {
                return ResourceManager.GetString("strBusinessProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Business Process Type.
        /// </summary>
        internal static string strBusinessProcessType {
            get {
                return ResourceManager.GetString("strBusinessProcessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Catalogo.
        /// </summary>
        internal static string strCatalogType {
            get {
                return ResourceManager.GetString("strCatalogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        internal static string strCode {
            get {
                return ResourceManager.GetString("strCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Banco.
        /// </summary>
        internal static string strCodeBank {
            get {
                return ResourceManager.GetString("strCodeBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Cuenta Bancaria.
        /// </summary>
        internal static string strCodeBankAccount {
            get {
                return ResourceManager.GetString("strCodeBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Catálogo Estados Globales.
        /// </summary>
        internal static string strCodeCatalogLifecycleStatus {
            get {
                return ResourceManager.GetString("strCodeCatalogLifecycleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Tipo Catalogo.
        /// </summary>
        internal static string strCodeCatalogType {
            get {
                return ResourceManager.GetString("strCodeCatalogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prorrogas Actuales.
        /// </summary>
        internal static string strCodeCodeContractCurrentRenewalNumber {
            get {
                return ResourceManager.GetString("strCodeCodeContractCurrentRenewalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Entidad.
        /// </summary>
        internal static string strCodeCompany {
            get {
                return ResourceManager.GetString("strCodeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Direccion de Entidad.
        /// </summary>
        internal static string strCodeCompanyAddress {
            get {
                return ResourceManager.GetString("strCodeCompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Tipo Entidad.
        /// </summary>
        internal static string strCodeCompanyType {
            get {
                return ResourceManager.GetString("strCodeCompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Contrato.
        /// </summary>
        internal static string strCodeContract {
            get {
                return ResourceManager.GetString("strCodeContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha introducido no cumple con la fecha calculada.
        /// </summary>
        internal static string strCodeContractDate {
            get {
                return ResourceManager.GetString("strCodeContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cadencias Prorrogas(meses).
        /// </summary>
        internal static string strCodeContractFrequencyMonth {
            get {
                return ResourceManager.GetString("strCodeContractFrequencyMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Tipo Contratacion.
        /// </summary>
        internal static string strCodeContractGroup {
            get {
                return ResourceManager.GetString("strCodeContractGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Contrato Detalle.
        /// </summary>
        internal static string strCodeContractLine {
            get {
                return ResourceManager.GetString("strCodeContractLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Contracto Detalle Beneficiario.
        /// </summary>
        internal static string strCodeContractLineEntidad {
            get {
                return ResourceManager.GetString("strCodeContractLineEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Contracto Detalle Impuesto.
        /// </summary>
        internal static string strCodeContractLineTaxes {
            get {
                return ResourceManager.GetString("strCodeContractLineTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Tipo Concepto.
        /// </summary>
        internal static string strCodeContractLineType {
            get {
                return ResourceManager.GetString("strCodeContractLineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Prorroga.
        /// </summary>
        internal static string strCodeContractRenewalDate {
            get {
                return ResourceManager.GetString("strCodeContractRenewalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Prorrogas.
        /// </summary>
        internal static string strCodeContractRenewalNumber {
            get {
                return ResourceManager.GetString("strCodeContractRenewalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Estado Contrato.
        /// </summary>
        internal static string strCodeContractState {
            get {
                return ResourceManager.GetString("strCodeContractState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Contrato Tipo.
        /// </summary>
        internal static string strCodeContractType {
            get {
                return ResourceManager.GetString("strCodeContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Moneda.
        /// </summary>
        internal static string strCodeCurrency {
            get {
                return ResourceManager.GetString("strCodeCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Inflacion.
        /// </summary>
        internal static string strCodeInflationTipo {
            get {
                return ResourceManager.GetString("strCodeInflationTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Metodo Pago.
        /// </summary>
        internal static string strCodePaymentMethods {
            get {
                return ResourceManager.GetString("strCodePaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Condicion pago.
        /// </summary>
        internal static string strCodePaymentTerm {
            get {
                return ResourceManager.GetString("strCodePaymentTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Tipo Producto.
        /// </summary>
        internal static string strCodeProductType {
            get {
                return ResourceManager.GetString("strCodeProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo SAP Tipo NIF.
        /// </summary>
        internal static string strCodeSAPTypeNIF {
            get {
                return ResourceManager.GetString("strCodeSAPTypeNIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Site.
        /// </summary>
        internal static string strCodeSite {
            get {
                return ResourceManager.GetString("strCodeSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Impuesto.
        /// </summary>
        internal static string strCodeTaxes {
            get {
                return ResourceManager.GetString("strCodeTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Tipo Contribuyente.
        /// </summary>
        internal static string strCodeTaxpayerType {
            get {
                return ResourceManager.GetString("strCodeTaxpayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Vista.
        /// </summary>
        internal static string strCodeView {
            get {
                return ResourceManager.GetString("strCodeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo estado del WorkFlow.
        /// </summary>
        internal static string strCodeWorkFlowStatus {
            get {
                return ResourceManager.GetString("strCodeWorkFlowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Estado Agrupacion.
        /// </summary>
        internal static string strCodeWorkFlowStatusGroup {
            get {
                return ResourceManager.GetString("strCodeWorkFlowStatusGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Estado del Seguimiento.
        /// </summary>
        internal static string strCodeWorkOrderTrakingStatus {
            get {
                return ResourceManager.GetString("strCodeWorkOrderTrakingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad.
        /// </summary>
        internal static string strCompany {
            get {
                return ResourceManager.GetString("strCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moneda.
        /// </summary>
        internal static string strCurrency {
            get {
                return ResourceManager.GetString("strCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo puede haber uno por defecto.
        /// </summary>
        internal static string strDefecto {
            get {
                return ResourceManager.GetString("strDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importacion.
        /// </summary>
        internal static string strImportTask {
            get {
                return ResourceManager.GetString("strImportTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Importacion.
        /// </summary>
        internal static string strImportType {
            get {
                return ResourceManager.GetString("strImportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inflacion.
        /// </summary>
        internal static string strInflation {
            get {
                return ResourceManager.GetString("strInflation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es pack.
        /// </summary>
        internal static string strIsPack {
            get {
                return ResourceManager.GetString("strIsPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Pais.
        /// </summary>
        internal static string strNameCountry {
            get {
                return ResourceManager.GetString("strNameCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string strProduct {
            get {
                return ResourceManager.GetString("strProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto con código.
        /// </summary>
        internal static string strProductWithCode {
            get {
                return ResourceManager.GetString("strProductWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string strProfile {
            get {
                return ResourceManager.GetString("strProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Program.
        /// </summary>
        internal static string strProgram {
            get {
                return ResourceManager.GetString("strProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ProjectLifeCycleStatus.
        /// </summary>
        internal static string strProjectLifeCycleStatus {
            get {
                return ResourceManager.GetString("strProjectLifeCycleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de prorroga.
        /// </summary>
        internal static string strProrrogas {
            get {
                return ResourceManager.GetString("strProrrogas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        internal static string strRol {
            get {
                return ResourceManager.GetString("strRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow.
        /// </summary>
        internal static string strWorkflow {
            get {
                return ResourceManager.GetString("strWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work Order.
        /// </summary>
        internal static string strWorkOrder {
            get {
                return ResourceManager.GetString("strWorkOrder", resourceCulture);
            }
        }
    }
}
